package com.form;
// Generated 2017-7-21 15:18:10 by Hibernate Tools 3.5.0.Final

import java.util.Date;


/**
 * OdWorkflowInstance generated by hbm2java
 */
public class OdBgInstance  {
    
    /**
     * serialVersionUID:TODO(用一句话描述这个变量表示什么).
     */
    private static final long serialVersionUID = 1L;
    
    private String instanceId;
    
    private Integer workflowId;
    
    private String workflowName;
    
    private String title;
    
    private String fileNum;
    
    private Integer initatorId;
    
    private String initatorName;
    
    private String initatorSecondname;
    
    private String deptCode;
    
    private String deptName;
    
    private String upperDeptcode;
    
    private String upperDeptname;
    
    private Date startDate;
    
    private Date endDate;
    
    private Integer parentInstanceId;
    
    private Integer status;
    
    private String groupId;
    
    private String docId;
    
    private String isAttention;
    
    private String isHuiQian;
    
    private String isBack;;
    
    private String userHanders;
    
    private String isTaiLd;
    private String xwStatus;
    //
    private String tmsStatus;
    //是否经过中心
    private String isZxBs;
    //是否经过中心领导审批
    private String isZxldSp;
    //实物附件标识
    private String substance;
    
    
    
    
    //工作项ID
    private String workitemId;
    
    
  //活动申请
    //项目
    private String proType;//(工会)项目
    private String totalCode;//(工会)台总字
    private String channelCode;//(工会)中心工会字
    private Integer applyStatus;//(工会)申请状态
    private String oid;//(工会)申请主键
    private String applicationTime;//(工会)申请的创建时间（申请时间）
    private String centerName;//(工会)所属单位（申请人的中心名称）
    private Integer isSecond;//(工会)是否是第二套流程
    private Integer isSecondReturn;//(工会)是否是第二套流程退办
    private Integer isLeaderSend;//(工会)是否是领导转发
    private String taskLoc;//(工会)任务描述
    
    public OdBgInstance() {
        
    }
    
    public OdBgInstance(String instanceId, Integer workflowId, String workflowName, String title, String fileNum,
            Integer initatorId, String initatorName, String initatorSecondname, String deptCode, String deptName,
            String upperDeptcode, String upperDeptname, Date startDate, Date endDate, Integer parentInstanceId, Integer status,
            String groupId, String docId, String isAttention, String isHuiQian, String isBack, String userHanders,
            String isTaiLd,String xwStatus,String tmsStatus,String isZxBs,String isZxldSp,String substance) {
        this.instanceId = instanceId;
        this.workflowId = workflowId;
        this.workflowName = workflowName;
        this.title = title;
        this.fileNum = fileNum;
        this.initatorId = initatorId;
        this.initatorName = initatorName;
        this.initatorSecondname = initatorSecondname;
        this.deptCode = deptCode;
        this.deptName = deptName;
        this.upperDeptcode = upperDeptcode;
        this.upperDeptname = upperDeptname;
        this.startDate = startDate;
        this.endDate = endDate;
        this.parentInstanceId = parentInstanceId;
        this.status = status;
        this.groupId = groupId;
        this.docId = docId;
        this.isAttention = isAttention;
        this.isHuiQian = isHuiQian;
        this.isBack = isBack;
        this.userHanders = userHanders;
        this.isTaiLd = isTaiLd;
        this.xwStatus=xwStatus;
        this.tmsStatus=tmsStatus;
        this.isZxBs=isZxBs;
        this.isZxldSp=isZxldSp;
        this.substance=substance;
    }
    
    public String getInstanceId() {
        return this.instanceId;
    }
    
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }
    
    public Integer getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }
    
    public String getWorkflowName() {
        return this.workflowName;
    }
    
    public void setWorkflowName(String workflowName) {
        this.workflowName = workflowName;
    }
    
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getFileNum() {
        return this.fileNum;
    }
    
    public void setFileNum(String fileNum) {
        this.fileNum = fileNum;
    }
    
    public Integer getInitatorId() {
        return this.initatorId;
    }
    
    public void setInitatorId(Integer initatorId) {
        this.initatorId = initatorId;
    }
    
    public String getInitatorName() {
        return this.initatorName;
    }
    
    public void setInitatorName(String initatorName) {
        this.initatorName = initatorName;
    }
    
    public String getInitatorSecondname() {
        return this.initatorSecondname;
    }
    
    public void setInitatorSecondname(String initatorSecondname) {
        this.initatorSecondname = initatorSecondname;
    }
    
    public String getDeptCode() {
        return deptCode;
    }
    
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }
    
    public String getDeptName() {
        return deptName;
    }
    
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }
    
    public String getUpperDeptcode() {
        return upperDeptcode;
    }
    
    public void setUpperDeptcode(String upperDeptcode) {
        this.upperDeptcode = upperDeptcode;
    }
    
    public String getUpperDeptname() {
        return upperDeptname;
    }
    
    public void setUpperDeptname(String upperDeptname) {
        this.upperDeptname = upperDeptname;
    }
    
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    public Integer getParentInstanceId() {
        return this.parentInstanceId;
    }
    
    public void setParentInstanceId(Integer parentInstanceId) {
        this.parentInstanceId = parentInstanceId;
    }
    
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    
    public String getGroupId() {
        return groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }
    
    public String getDocId() {
        return docId;
    }
    
    public void setDocId(String docId) {
        this.docId = docId;
    }
    
    public String getIsAttention() {
        return isAttention;
    }
    
    public void setIsAttention(String isAttention) {
        this.isAttention = isAttention;
    }
    
    public String getIsHuiQian() {
        return isHuiQian;
    }
    
    public void setIsHuiQian(String isHuiQian) {
        this.isHuiQian = isHuiQian;
    }
    
    public String getIsBack() {
        return isBack;
    }
    
    public void setIsBack(String isBack) {
        this.isBack = isBack;
    }
    
    public String getUserHanders() {
        return userHanders;
    }
    
    public void setUserHanders(String userHanders) {
        this.userHanders = userHanders;
    }

    public String getIsTaiLd() {
        return isTaiLd;
    }

    public void setIsTaiLd(String isTaiLd) {
        this.isTaiLd = isTaiLd;
    }

    public String getXwStatus() {
        return xwStatus;
    }

    public void setXwStatus(String xwStatus) {
        this.xwStatus = xwStatus;
    }

    public String getTmsStatus() {
        return tmsStatus;
    }

    public void setTmsStatus(String tmsStatus) {
        this.tmsStatus = tmsStatus;
    }

    public String getIsZxBs() {
        return isZxBs;
    }

    public void setIsZxBs(String isZxBs) {
        this.isZxBs = isZxBs;
    }

    public String getIsZxldSp() {
        return isZxldSp;
    }

    public void setIsZxldSp(String isZxldSp) {
        this.isZxldSp = isZxldSp;
    }

    public String getSubstance() {
        return substance;
    }

    public void setSubstance(String substance) {
        this.substance = substance;
    }

	public String getProType() {
		return proType;
	}

	public void setProType(String proType) {
		this.proType = proType;
	}

    public String getWorkitemId() {
        return workitemId;
    }

    public void setWorkitemId(String workitemId) {
        this.workitemId = workitemId;
    }

	public String getTotalCode() {
		return totalCode;
	}

	public void setTotalCode(String totalCode) {
		this.totalCode = totalCode;
	}

	public String getChannelCode() {
		return channelCode;
	}

	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	public Integer getApplyStatus() {
		return applyStatus;
	}

	public void setApplyStatus(Integer applyStatus) {
		this.applyStatus = applyStatus;
	}

	public String getOid() {
		return oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	public String getApplicationTime() {
		return applicationTime;
	}

	public void setApplicationTime(String applicationTime) {
		this.applicationTime = applicationTime;
	}

	public String getCenterName() {
		return centerName;
	}

	public void setCenterName(String centerName) {
		this.centerName = centerName;
	}

	public Integer getIsSecond() {
		return isSecond;
	}

	public void setIsSecond(Integer isSecond) {
		this.isSecond = isSecond;
	}

	public Integer getIsSecondReturn() {
		return isSecondReturn;
	}

	public void setIsSecondReturn(Integer isSecondReturn) {
		this.isSecondReturn = isSecondReturn;
	}

	public Integer getIsLeaderSend() {
		return isLeaderSend;
	}

	public void setIsLeaderSend(Integer isLeaderSend) {
		this.isLeaderSend = isLeaderSend;
	}

	public String getTaskLoc() {
		return taskLoc;
	}

	public void setTaskLoc(String taskLoc) {
		this.taskLoc = taskLoc;
	}
}
